### ISSUE TITLE
.dotfiles or .directories/ should be skipped

### ISSUE THREAD

**Issue by jmartsch** [baumrock/RockMigrations#4] opened 2022-08-03 09:34 UTC
I often have directories or files with a preceding dot like "site/modules/.TracyDebugger". I think they are obsolete files coming from an update of modules or something like that.
However I think, that these directories and files should be excluded from a migration.

What you think about that?

**Comment by BernhardBaumrock** [comment] 2022-08-03 13:43
What do you mean by "excluded from a migration?"
TracyDebugger does not have any migrations in it, so it will not run any migrations anyhow?

**Comment by jmartsch** [comment] 2022-08-03 13:51
TracyDebugger was just an example. Imagine you got a module with a migration in it. 

Then you upgrade the module via ProcessWires admin (this might not apply to you, as you install modules via git or RockMigrations, but I think is is applicable for others).

After upgrading the module there is a module folder prefixed with a dot, and the normal updated module.
For example after running an upgrade I have these two folders:
![image](https://user-images.githubusercontent.com/551551/182625030-06758925-9d61-4267-a086-9fc678eaa573.png)


As RockMigrations traverses through all folders in site/modules the migration from the old module would be run, which is not desired.

**Comment by BernhardBaumrock** [comment] 2022-08-08 13:56
Hey @jmartsch thanks for the report and sorry for the delay... I did not get any notifications... I understand now.

Do you THINK that this is the case or did you actually try that out? I don't think that what you are saying is the case, because RockMigrations does already skip those dot-folders. I'll close the issue. If you think the issue exists please open it and provide a reproducable example. Thanks!

**Closed by BernhardBaumrock** 2022-08-08 13:56 UTC
